name = "CancerImagingArchive"
uuid = "1c555f4c-8d6b-45c3-bbc1-c64989f538fe"
version = "1.1.4"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
CSV = "0.6, 0.7, 0.8, 0.9, 0.10"
DataFrames = "0.21, 0.22, 1.0"
HTTP = "^0.8.6, 0.9, 1.7"
JSON = "^0.21"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
